/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.servicio.ServicioPersona;
import javax.swing.ButtonGroup;

import modelo.enums.TipoDiscapacidad;
import vista.utilidades.UtilidadesComponente;

/**
 *
 * @author franzandresflores
 */
public class FrmRegistro extends javax.swing.JDialog {

    private ServicioPersona sn = new ServicioPersona();
    
    public FrmRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarCombo();
        ButtonGroup botonGrupo = new ButtonGroup();
        botonGrupo.add(rd_si);
        botonGrupo.add(rd_no);
    }
    
    
    private void limpiar() {
        cbx_tipo.setSelectedIndex(0);
    }
    
    private void cargarObjeto() {
        sn.obtenerPersona().setCedula(txt_cedula.getText());
        sn.obtenerPersona().setNombre(txt_nombre.getText());
        sn.obtenerPersona().setDireccion(txt_direccion.getText());
        sn.obtenerPersona().setTelefono(txt_telefono.getText());
        sn.obtenerPersona().setCiudad(txt_ciudad.getText());
        if (rd_si.isSelected()) {
            sn.obtenerPersona().setTiene_discacidad(true);
            sn.obtenerPersona().setPorcentaje(txt_porcentaje.getText());
            sn.obtenerPersona().setTipo((TipoDiscapacidad) cbx_tipo.getSelectedItem());
        }else if (rd_no.isSelected()) {
            sn.obtenerPersona().setTiene_discacidad(false);
            sn.obtenerPersona().setPorcentaje("Ninguna");
            sn.obtenerPersona().setTipo((TipoDiscapacidad) cbx_tipo.getSelectedItem());
        }
    }
    
    private void mostrarCombo(){
        if (rd_si.isSelected()) {
            porcentaje.setVisible(true);
            tipo.setVisible(true);
            cbx_tipo.setVisible(true);
            txt_porcentaje.setVisible(true);
        } else if (rd_no.isSelected()) {
            porcentaje.setVisible(false);
            tipo.setVisible(false);
            cbx_tipo.setVisible(false);
            txt_porcentaje.setVisible(false);
        }
    }

    private void cargarCombo() {
        UtilidadesComponente.cargarcomboTipo(cbx_tipo);
        cbx_tipo.updateUI();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rd_no = new javax.swing.JRadioButton();
        rd_si = new javax.swing.JRadioButton();
        btn_cancelar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_ciudad = new javax.swing.JTextField();
        porcentaje = new javax.swing.JLabel();
        txt_porcentaje = new javax.swing.JTextField();
        tipo = new javax.swing.JLabel();
        cbx_tipo = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO PERSONA");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 430, 40);

        jLabel2.setText("Cédula");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 70, 20);
        getContentPane().add(txt_cedula);
        txt_cedula.setBounds(90, 40, 170, 30);

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 90, 70, 20);
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(90, 80, 310, 30);

        jLabel4.setText("Dirección");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 70, 20);
        getContentPane().add(txt_direccion);
        txt_direccion.setBounds(90, 120, 310, 30);

        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 170, 70, 20);
        getContentPane().add(txt_telefono);
        txt_telefono.setBounds(90, 160, 120, 30);

        jLabel6.setText("Discapacidad");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 210, 90, 20);

        rd_no.setSelected(true);
        rd_no.setText("No");
        rd_no.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rd_noStateChanged(evt);
            }
        });
        rd_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_noActionPerformed(evt);
            }
        });
        getContentPane().add(rd_no);
        rd_no.setBounds(130, 210, 50, 23);

        rd_si.setText("Si");
        rd_si.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rd_siItemStateChanged(evt);
            }
        });
        rd_si.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rd_siStateChanged(evt);
            }
        });
        rd_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_siActionPerformed(evt);
            }
        });
        getContentPane().add(rd_si);
        rd_si.setBounds(270, 210, 43, 23);

        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar);
        btn_cancelar.setBounds(250, 380, 130, 50);

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar);
        btn_guardar.setBounds(40, 380, 130, 50);

        jLabel7.setText("Ciudad");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 166, 50, 20);
        getContentPane().add(txt_ciudad);
        txt_ciudad.setBounds(270, 160, 120, 30);

        porcentaje.setText("Porcentaje");
        getContentPane().add(porcentaje);
        porcentaje.setBounds(20, 270, 80, 20);
        getContentPane().add(txt_porcentaje);
        txt_porcentaje.setBounds(160, 270, 140, 30);

        tipo.setText("Tipo Discapacidad");
        getContentPane().add(tipo);
        tipo.setBounds(20, 310, 130, 30);

        cbx_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbx_tipo);
        cbx_tipo.setBounds(160, 310, 140, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(30, 250, 360, 10);

        setSize(new java.awt.Dimension(417, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
       if (!UtilidadesComponente.mostrarError(txt_cedula, "Falta este dato", 'r')
            && !UtilidadesComponente.mostrarError(txt_nombre, "Falta este dato", 'r')
            && !UtilidadesComponente.mostrarError(txt_direccion, "Falta este dato", 'r')
            && !UtilidadesComponente.mostrarError(txt_telefono, "Falta este dato", 'r')) {
            cargarObjeto();
            if (sn.obtenerPersona().getId() == null) {
              if (sn.guardar()) {                   
                    UtilidadesComponente.mensajeOk("OK", "Se ha guardado correctamente");
                } else {
                    UtilidadesComponente.mensajeOk("ERROR", "No se pudo guardar correctamente");
                }
            }
        } 
        
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void rd_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_siActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rd_siActionPerformed

    private void rd_siItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rd_siItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_siItemStateChanged

    private void rd_siStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rd_siStateChanged
        // TODO add your handling code here:
        mostrarCombo();
    }//GEN-LAST:event_rd_siStateChanged

    private void rd_noStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rd_noStateChanged
        // TODO add your handling code here:
        mostrarCombo();
    }//GEN-LAST:event_rd_noStateChanged

    private void rd_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_noActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRegistro dialog = new FrmRegistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JComboBox<String> cbx_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel porcentaje;
    private javax.swing.JRadioButton rd_no;
    private javax.swing.JRadioButton rd_si;
    private javax.swing.JLabel tipo;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_ciudad;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_porcentaje;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
