/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author franzandresflores
 */
public class Inicio extends javax.swing.JFrame {

    public Inicio() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mn_registrar = new javax.swing.JMenuItem();
        mn_listado = new javax.swing.JMenuItem();
        mn_estadisiticas = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(null);

        jMenu1.setText("Inicio");

        mn_registrar.setText("Registrar Persona");
        mn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_registrarActionPerformed(evt);
            }
        });
        jMenu1.add(mn_registrar);

        mn_listado.setText("Listado Persona");
        mn_listado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_listadoActionPerformed(evt);
            }
        });
        jMenu1.add(mn_listado);

        mn_estadisiticas.setText("Estadisticas");
        mn_estadisiticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_estadisiticasActionPerformed(evt);
            }
        });
        jMenu1.add(mn_estadisiticas);

        jMenuBar1.add(jMenu1);

        salir.setText("Ayuda");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenuBar1.add(salir);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(587, 404));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_registrarActionPerformed
        // TODO add your handling code here:
       new FrmRegistro(this,true).setVisible(true);
    }//GEN-LAST:event_mn_registrarActionPerformed

    private void mn_listadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_listadoActionPerformed
        // TODO add your handling code here:
        new FrmListado(this,true).setVisible(true);
    }//GEN-LAST:event_mn_listadoActionPerformed

    private void mn_estadisiticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_estadisiticasActionPerformed
        // TODO add your handling code here:
        new FrmEstadisiticas(this,true).setVisible(true);
    }//GEN-LAST:event_mn_estadisiticasActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mn_estadisiticas;
    private javax.swing.JMenuItem mn_listado;
    private javax.swing.JMenuItem mn_registrar;
    private javax.swing.JMenu salir;
    // End of variables declaration//GEN-END:variables
}
